// Цыганские карты (36) — упрощённая классика. Традиционные значения Тарот Романеско в краткой редакции.
window.DECK_GYPSY = [
  { id: 'g01', name: 'Всадник',     symbol: '🃁', upright: 'Новость, приход, движение. Кто-то скачет к вам.', reversed: 'Задержка, неверный путь.' },
  { id: 'g02', name: 'Клевер',      symbol: '🍀', upright: 'Удача в мелочах, надежда.', reversed: 'Упущенный шанс, мелкая досада.' },
  { id: 'g03', name: 'Корабль',     symbol: '⛵', upright: 'Путешествие, перемены, дальнее.', reversed: 'Задержка, тоска.' },
  { id: 'g04', name: 'Дом',         symbol: '🏠', upright: 'Семья, уют, корни.', reversed: 'Разлад, переезд.' },
  { id: 'g05', name: 'Дерево',      symbol: '🌳', upright: 'Здоровье, рост, долгая жизнь.', reversed: 'Болезнь, торопливость.' },
  { id: 'g06', name: 'Тучи',        symbol: '☁️', upright: 'Сомнение, туман, неясность.', reversed: 'Прояснение.' },
  { id: 'g07', name: 'Змея',        symbol: '🐍', upright: 'Зависть, интрига, обман.', reversed: 'Обман раскрыт.' },
  { id: 'g08', name: 'Гроб',        symbol: '⚰️', upright: 'Конец, прощание.', reversed: 'Возрождение после потери.' },
  { id: 'g09', name: 'Букет',       symbol: '💐', upright: 'Дар, радость, встреча.', reversed: 'Недолгая радость.' },
  { id: 'g10', name: 'Коса',        symbol: '🌾', upright: 'Резкий разрыв.', reversed: 'Отсрочка.' },
  { id: 'g11', name: 'Метла',       symbol: '🧹', upright: 'Ссора, раздор, мелкий спор.', reversed: 'Утихание.' },
  { id: 'g12', name: 'Птицы',       symbol: '🐦', upright: 'Разговор, весточка, пара.', reversed: 'Сплетни, ссора.' },
  { id: 'g13', name: 'Ребёнок',     symbol: '🧒', upright: 'Начало, новое.', reversed: 'Незрелость.' },
  { id: 'g14', name: 'Лиса',        symbol: '🦊', upright: 'Хитрость, лесть.', reversed: 'Ложь вскрыта.' },
  { id: 'g15', name: 'Медведь',     symbol: '🐻', upright: 'Сила, покровитель.', reversed: 'Ревность.' },
  { id: 'g16', name: 'Звёзды',      symbol: '✨', upright: 'Сеть, надежда.', reversed: 'Потерянный путь.' },
  { id: 'g17', name: 'Аист',        symbol: '🕊️', upright: 'Перемена, обновление.', reversed: 'Задержка.' },
  { id: 'g18', name: 'Собака',      symbol: '🐕', upright: 'Верный друг.', reversed: 'Предательство.' },
  { id: 'g19', name: 'Башня',       symbol: '🗼', upright: 'Одиночество, учреждение.', reversed: 'Опора.' },
  { id: 'g20', name: 'Сад',         symbol: '🌷', upright: 'Общество, праздник.', reversed: 'Ссора в обществе.' },
  { id: 'g21', name: 'Гора',        symbol: '⛰️', upright: 'Препятствие.', reversed: 'Препятствие пройдено.' },
  { id: 'g22', name: 'Развилка',    symbol: '🛤️', upright: 'Выбор.', reversed: 'Колебание.' },
  { id: 'g23', name: 'Мыши',        symbol: '🐭', upright: 'Потеря, мелочи.', reversed: 'Возврат.' },
  { id: 'g24', name: 'Сердце',      symbol: '❤️', upright: 'Любовь.', reversed: 'Тоска.' },
  { id: 'g25', name: 'Кольцо',      symbol: '💍', upright: 'Союз, обязательство.', reversed: 'Разрыв.' },
  { id: 'g26', name: 'Книга',       symbol: '📖', upright: 'Тайна, знание.', reversed: 'Тайна раскрыта.' },
  { id: 'g27', name: 'Письмо',      symbol: '✉️', upright: 'Известие.', reversed: 'Задержка.' },
  { id: 'g28', name: 'Мужчина',     symbol: '👤', upright: 'Мужчина в раскладе.', reversed: 'Сомнение в нём.' },
  { id: 'g29', name: 'Женщина',     symbol: '👤', upright: 'Женщина в раскладе.', reversed: 'Сомнение в ней.' },
  { id: 'g30', name: 'Лилия',       symbol: '🌸', upright: 'Зрелость, чистота.', reversed: 'Незрелость.' },
  { id: 'g31', name: 'Солнце',      symbol: '☀️', upright: 'Радость, успех.', reversed: 'Пауза.' },
  { id: 'g32', name: 'Луна',        symbol: '🌙', upright: 'Слава, интуиция.', reversed: 'Сомнение.' },
  { id: 'g33', name: 'Ключ',        symbol: '🔑', upright: 'Разгадка, выход.', reversed: 'Ключ утерян.' },
  { id: 'g34', name: 'Рыба',        symbol: '🐟', upright: 'Деньги, поток.', reversed: 'Утечка.' },
  { id: 'g35', name: 'Якорь',       symbol: '⚓', upright: 'Стабильность.', reversed: 'Застой.' },
  { id: 'g36', name: 'Крест',       symbol: '✝️', upright: 'Ноша, испытание.', reversed: 'Ноша снята.' }
];
// У цыганских/ленорман значения на reversals короче — добавим универсальный shadow
window.DECK_GYPSY.forEach(c => { c.shadow = 'Тень карты — то, что вы не хотите в ней видеть, но оно есть.'; });
